import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The short sounds a run gives back: one for right, one for wrong, and a
/// click under every key that actually did something.
///
/// A tablet lying flat on the table swallows the vibration, and a child who
/// is looking at the keypad rather than at the answer box misses the colour
/// too. The sound is the third channel, and the shortest one.
///
/// The files are generated by `tool/make_sounds.py` rather than downloaded:
/// two sine tones are a few lines of arithmetic, need no licence and weigh
/// twenty kilobytes together.
class FeedbackSounds {
  /// Kept warm: creating a player on the first wrong answer would delay the
  /// very sound that is supposed to be immediate.
  final AudioPlayer _correct = AudioPlayer(playerId: 'mt-correct');
  final AudioPlayer _wrong = AudioPlayer(playerId: 'mt-wrong');
  final AudioPlayer _key = AudioPlayer(playerId: 'mt-key');
  bool _ready = false;

  Future<void> warmUp() async {
    if (_ready) return;
    _ready = true;
    try {
      await _correct.setReleaseMode(ReleaseMode.stop);
      await _wrong.setReleaseMode(ReleaseMode.stop);
      await _key.setReleaseMode(ReleaseMode.stop);
      await _correct.setSource(AssetSource('sound/correct.wav'));
      await _wrong.setSource(AssetSource('sound/wrong.wav'));
      await _key.setSource(AssetSource('sound/key.wav'));
    } catch (error) {
      // A device without working audio must not take the practice screen
      // down with it - the run matters, the sound does not.
      debugPrint('Rückmeldungstöne nicht verfügbar: $error');
      _ready = false;
    }
  }

  Future<void> _play(AudioPlayer player) async {
    if (!_ready) return;
    try {
      await player.seek(Duration.zero);
      await player.resume();
    } catch (error) {
      debugPrint('Ton konnte nicht abgespielt werden: $error');
    }
  }

  void playCorrect() => unawaited(_play(_correct));

  void playWrong() => unawaited(_play(_wrong));

  /// The click under a key. It fires far more often than the other two, so it
  /// is the one that must never get in the way: 35 ms, no pitch to speak of,
  /// and well under half their volume.
  void playKey() => unawaited(_play(_key));

  Future<void> dispose() async {
    await _correct.dispose();
    await _wrong.dispose();
    await _key.dispose();
  }
}
