import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The short sounds a run gives back: one for right, one for wrong, and a
/// click under every key that actually did something.
///
/// A tablet lying flat on the table swallows the vibration, and a child who
/// is looking at the keypad rather than at the answer box misses the colour
/// too. The sound is the third channel, and the shortest one.
///
/// The files are generated by `tool/make_sounds.py` rather than downloaded:
/// two sine tones are a few lines of arithmetic, need no licence and weigh
/// twenty kilobytes together.
class FeedbackSounds {
  /// Kept warm: creating a player on the first wrong answer would delay the
  /// very sound that is supposed to be immediate.
  ///
  /// **No fixed player ids.** They used to be 'mt-correct', 'mt-wrong' and
  /// 'mt-key', which reads nicely in a log and cost the sound outright: the
  /// practice screen built a FeedbackSounds per run and threw the old one
  /// away without awaiting its dispose, so the next run registered players
  /// under ids that were still being torn down. The reply to the second
  /// registration never came, `warmUp` never returned, and everything after
  /// it was silent. Measured on Linux: run 1 plays, run 2 hangs, run 3 plays,
  /// run 4 hangs. The package hands out a uuid when it is not told otherwise.
  final AudioPlayer _correct = AudioPlayer();
  final AudioPlayer _wrong = AudioPlayer();
  final AudioPlayer _key = AudioPlayer();
  bool _ready = false;

  FeedbackSounds() {
    // No position polling. Every player starts life with a
    // [FramePositionUpdater] that asks the platform for the playback position
    // **once per frame** while a sound is running, plus once more on every
    // stop. Nothing here draws a progress bar - the sounds are between 35 and
    // 300 ms long - so all of that is pure traffic on the channel.
    //
    // On Linux it is worse than waste. Each poll is a GStreamer position query
    // on the same thread that performs the playback state changes, and the
    // updater restarts its frame-callback chain on every resume without
    // reliably ending the previous one: after a few dozen key presses several
    // chains poll in parallel, and the resume that should start the next
    // click queues up behind them. That is what "der Ton verschwindet" looks
    // like from the outside.
    _correct.positionUpdater = null;
    _wrong.positionUpdater = null;
    _key.positionUpdater = null;
  }

  /// Why the sound is not working, if it is not.
  ///
  /// Kept rather than only logged: "der Ton geht nicht" is impossible to act
  /// on, and on a tablet there is no console to read. The parent area can
  /// show this.
  String? lastError;

  bool get isReady => _ready;

  Future<bool> warmUp() async {
    if (_ready) return true;
    try {
      await _correct.setReleaseMode(ReleaseMode.stop);
      await _wrong.setReleaseMode(ReleaseMode.stop);
      await _key.setReleaseMode(ReleaseMode.stop);
      await _correct.setSource(AssetSource('sound/correct.wav'));
      await _wrong.setSource(AssetSource('sound/wrong.wav'));
      await _key.setSource(AssetSource('sound/key.wav'));
      _ready = true;
      lastError = null;
    } catch (error) {
      // A device without working audio must not take the practice screen
      // down with it - the run matters, the sound does not.
      debugPrint('Rückmeldungstöne nicht verfügbar: $error');
      lastError = '$error';
      _ready = false;
    }
    return _ready;
  }

  /// Rewinds with [AudioPlayer.stop] rather than [AudioPlayer.seek].
  ///
  /// `seek` waits for the platform's `onSeekComplete` event, with a thirty
  /// second timeout. Android's MediaPlayer does not reliably report a seek
  /// that goes nowhere - and after a sound has finished, the plugin has
  /// already rewound it to zero, so every replay was exactly such a seek.
  /// The await never returned, `resume()` below it never ran, and each sound
  /// was audible exactly once per run.
  ///
  /// `stop()` rewinds natively without waiting for an event, and with
  /// [ReleaseMode.stop] the source stays prepared.
  Future<void> _play(AudioPlayer player) async {
    if (!_ready) return;
    try {
      await player.stop();
      await player.resume();
      lastError = null;
    } catch (error) {
      debugPrint('Ton konnte nicht abgespielt werden: $error');
      lastError = '$error';
    }
  }

  void playCorrect() => unawaited(_play(_correct));

  void playWrong() => unawaited(_play(_wrong));

  /// The click under a key. It fires far more often than the other two, so it
  /// is the one that must never get in the way: 35 ms, no pitch to speak of,
  /// and well under half their volume.
  void playKey() => unawaited(_play(_key));

  /// Plays the click [plays] times and reports how many actually finished.
  ///
  /// A completion event only arrives for a sound that really ran, so this
  /// measures the symptom instead of asking somebody to listen carefully:
  /// "8 von 10" says something, "der Ton geht nicht" does not.
  Future<({int played, int expected})> selfTest({int plays = 10}) async {
    if (!await warmUp()) return (played: 0, expected: plays);

    var completed = 0;
    final subscription = _key.onPlayerComplete.listen((_) => completed++);
    try {
      for (var i = 0; i < plays; i++) {
        playKey();
        await Future<void>.delayed(const Duration(milliseconds: 200));
      }
      // The last one still needs its moment to finish and report.
      await Future<void>.delayed(const Duration(milliseconds: 250));
    } finally {
      await subscription.cancel();
    }
    return (played: completed, expected: plays);
  }

  Future<void> dispose() async {
    await _correct.dispose();
    await _wrong.dispose();
    await _key.dispose();
  }
}
